version: '3'

services:
  go-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - go-service-network

networks:
  go-service-network:
    driver: "bridge"
